[package]
name = "meson-contracts-aptos"
version = "0.1.0"

[dependencies]
SupraFramework = { git = "https://github.com/Entropy-Foundation/aptos-core.git", subdir = "aptos-move/framework/supra-framework", rev = "dev" }

[addresses]
std = "0x1"
aptos_framework = "0x1"
Meson = "0x"
